name: Ping
env:
  REPO_OWNER: andovnar2021
  REPO_NAME: testproject
  GITHUB_TOKEN: ${{ secrets.TOKENW }}
on:
  repository_dispatch:
    types: [run-ping]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
#       - name: Mistake
#         run: cat efdevrew
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

